name: TestTrigger

on:
  pull_request:
    branches:
      - main
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: E2ETest
        run: |
          curl -X POST https://api.github.com/repos/Mega61/saviaE2Etesting/actions/workflows/E2Etesting.yml/dispatches \
          -H 'Accept: application/vnd.github+json' \
          -u ${{ secrets.GH_PAT }} \
          --data '{"ref":"main"}'
      - uses: actions/checkout@v3
